site_name: Genshin Time Splitter
site_url: https://saipan-fez.github.io/GenshinTimeSplitter
repo_url: https://github.com/saipan-fez/GenshinTimeSplitter

theme:
  name: material
  palette:
    primary: white
  icon:
    repo: fontawesome/brands/github
  features:
    - header.autohide
    - navigation.tabs

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 日本語
      link: /
      lang: ja
  social:
    - icon: fontawesome/brands/twitter
      link: https://x.com/saipan_fez
      name: saipan_fez on Twitter

plugins:
  - search:
      lang: 'ja'
  - i18n:
      default_language: ja
      languages:
        en: English
        ja: 日本語

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
