name: build

on:
  workflow_dispatch:
  pull_request: 
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - 'v*'

defaults:
  run:
    shell: pwsh

jobs:

  build:
    runs-on: windows-latest
    env:
      SOLUTION_FILE: GenshinTimeSplitter.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore the application
      run: msbuild ${{ env.SOLUTION_FILE }} /t:Restore /p:Configuration=Release

    - name: Publish the application to folder
      run: msbuild ${{ env.SOLUTION_FILE }} /t:publish /p:Configuration=Release /p:PublishDir=publish /p:PublishProfile=win10-x64

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GenshinTimeSplitter_x64
        path: ./GenshinTimeSplitter/publish/*

  release:
    runs-on: windows-latest
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Get version
      id: version
      run: |
        $path = "GenshinTimeSplitter\GenshinTimeSplitter.csproj"
        [xml]$csproj = Get-Content $path
        $version = $csproj.Project.PropertyGroup.FileVersion
        Write-Output "version=$version" >> $Env:GITHUB_OUTPUT
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: GenshinTimeSplitter_x64
        path: ./x64
    - name: Zip artifacts
      run: Compress-Archive -Path ./x64/* -DestinationPath ./GenshinTimeSplitter_x64.zip
    - name: release
      uses: actions/create-release@v1.1.4
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./GenshinTimeSplitter_x64.zip
        asset_name: GenshinTimeSplitter_x64.zip
        asset_content_type: application/zip
